Lang model TCK
eclipse-ee4j/odi pull request #14
Opened 2022-03-16 15:04 UTC by dstepanov

Lang model TCK should pass after there is a new option to skip type annotations checks.
PR implements a custom Annotation model based on the annotation processor which is similar to reflection and TCK requirements. We might want to support both implementations Micronaut/Reflection with some kind of switch.

2022-03-17 06:49 UTC, dstepanov commented
The build is based on https://github.com/eclipse-ee4j/cdi-tck/pull/352

2022-03-18 15:59 UTC, graemerocher requested changes

2022-03-18 15:59 UTC, graemerocher commented on build.gradle
> +        mavenLocal()
Remove this

2022-03-18 15:59 UTC, graemerocher commented on processor-cdi/src/main/java/com/oracle/odi/cdi/processor/extensions/AnnotationInfoImpl.java
>  class AnnotationInfoImpl implements AnnotationInfo {
Add `@Internal`

2022-03-18 15:59 UTC, graemerocher commented on processor-cdi/src/main/java/com/oracle/odi/cdi/processor/extensions/AnnotationInfoImpl.java
> +        return annotationValue.get(name, Object.class).isPresent();
Why was this necessary?

2022-03-23 13:38 UTC, dstepanov commented on processor-cdi/src/main/java/com/oracle/odi/cdi/processor/extensions/AnnotationInfoImpl.java
> +        return annotationValue.get(name, Object.class).isPresent();
This actually returns a different value for the repeatable annotation

2022-03-23 17:44 UTC, merged